name:                soapCalc
version:             0.1.0.0
github:              "githubuser/soapCalc"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/soapCalc#readme>

dependencies:
- base >= 4.7 && < 5
- persistent >= 2.7.1
- persistent-sqlite
- persistent-template
- monad-logger
- text
- time
- optparse-applicative >= 0.14.2.0
- gtk3 >= 0.14.9
- transformers  >= 0.5.2.0

library:
  source-dirs: src

executables:
  soapCalc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - soapCalc

tests:
  soapCalc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - soapCalc
